# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Curso'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='d_requisito',
            field=models.ManyToManyField(blank=True, null=True, to='App.Disciplina'),
        ),
    ]
