# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20171105_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='disciplina',
            new_name='curso',
        ),
    ]
